"""Stable morphology columns and distance feature contracts."""

MORPH_COLUMNS = {
    "morphology_class",
    "morphology_compactness",
    "morphology_aspect",
    "morphology_edge_complexity",
    "morphology_bbox_fill",
    "morphology_symmetry",
    "morphology_branching",
    "morphology_filament_score",
    "morphology_lattice_score",
    "morphology_change_rate",
    "morphology_stability_ticks",
}

NUMERIC_COLUMNS = [
    "morphology_compactness",
    "morphology_aspect",
    "morphology_edge_complexity",
    "morphology_bbox_fill",
    "morphology_symmetry",
    "morphology_branching",
    "morphology_filament_score",
    "morphology_lattice_score",
    "morphology_change_rate",
    "morphology_stability_ticks",
    "evo_stress",
    "evo_adapt",
    "evo_pressure",
    "evo_extinction_risk",
    "knowledge_score",
    "feedback_score",
    "emergence_score",
    "validation_quality",
    "objects",
    "largest",
    "total_living_mass",
    "stability_index",
    "bbox_min_x", "bbox_max_x", "bbox_min_y", "bbox_max_y",
    "bbox_width", "bbox_height",
    "top_edge_fill", "right_edge_fill", "bottom_edge_fill", "left_edge_fill",
    "top_edge_run", "right_edge_run", "bottom_edge_run", "left_edge_run",
]

STATIC_DISTANCE_FEATURES = [
    "dominant_share",
    "morphology_entropy",
    "transition_rate_per_10k_ticks",
    "morphological_complexity_index",
    "morphology_compactness.mean",
    "morphology_aspect.mean",
    "morphology_edge_complexity.mean",
    "morphology_bbox_fill.mean",
    "morphology_symmetry.mean",
    "morphology_branching.mean",
    "morphology_filament_score.mean",
    "morphology_lattice_score.mean",
    "morphology_change_rate.mean",
    "stability_index.mean",
    "objects.mean",
    "total_living_mass.mean",
]

DYNAMIC_FEATURES = [
    "early_mci",
    "mid_mci",
    "late_mci",
    "mci_delta",
    "early_branching",
    "late_branching",
    "branching_delta",
    "early_edge",
    "late_edge",
    "edge_delta",
    "early_change_rate",
    "late_change_rate",
    "change_rate_delta",
    "trajectory_volatility",
    "trajectory_maturity",
    "trajectory_persistence",
]

BEHAVIOUR_FEATURES = [
    "behaviour_volatility",
    "behaviour_drift_strength",
    "behaviour_oscillation",
    "behaviour_complexity_slope",
    "behaviour_branching_slope",
    "behaviour_edge_slope",
    "behaviour_filament_slope",
    "behaviour_lattice_slope",
    "behaviour_change_slope",
    "behaviour_maturation_score",
    "behaviour_instability_score",
    "behaviour_pulse_score",
]
